# -------------------------------
# Prometheus Config
# -------------------------------
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: monitor
data:
  prometheus.yml: |
    global:
      scrape_interval: 5s
    scrape_configs:
      - job_name: "prometheus"
        metrics_path: /metrics   # PrometheusMetrics exposes metrics here by default
        static_configs:
          - targets: ["localhost:9090"]   # replace with your Flask host:port
      - job_name: "exporter-1"
        metrics_path: /metrics   # PrometheusMetrics exposes metrics here by default
        static_configs:
          - targets: ["exporter-svc:9100"]   # replace with your Flask host:port
      - job_name: "exporter-2"
        metrics_path: /metrics   # PrometheusMetrics exposes metrics here by default
        static_configs:
          - targets: ["exporter-svc:9100"]   # replace with your Flask host:port
      - job_name: "exporter-3"
        metrics_path: /metrics   # PrometheusMetrics exposes metrics here by default
        static_configs:
          - targets: ["exporter-svc:9100"]   # replace with your Flask host:port

---

# -------------------------------
# Prometheus
# -------------------------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-dep
  namespace: monitor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus-dep-pod
  template:
    metadata:
      labels:
        app: prometheus-dep-pod
    spec:
      containers:
        - name: prometheus
          image: prom/prometheus:v3.5.0
          args:
            - "--config.file=/etc/prometheus/prometheus.yml"
          ports:
            - containerPort: 9090
          volumeMounts:
            - name: prometheus-config-volume
              mountPath: /etc/prometheus
            - name: prometheus-storage
              mountPath: /prometheus
          resources:
              requests:
                memory: "64Mi"
                cpu: "250m"
              limits:
                memory: "128Mi"
                cpu: "500m"
      volumes:
        - name: prometheus-config-volume
          configMap:
            name: prometheus-config
        - name: prometheus-storage
          persistentVolumeClaim:
            claimName: prometheus-pvc

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-pvc
  namespace: monitor
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi

---

apiVersion: v1
kind: Service
metadata:
  name: prometheus-svc
  namespace: monitor
spec:
  type: NodePort
  selector:
    app: prometheus-dep-pod
  ports:
    - port: 9090
      targetPort: 9090
      nodePort: 32001
